openapi: "3.0.0"
info:
  version: 1.0.0
  title: Updated API
paths:
  /results:
    get:
      x-yc-apigateway-integration:
        type: cloud-functions
        function_id: d4***e9
        service_account_id: aj***1r
      operationId: function-for-user-requests
