openapi: 3.0.0
info:
  title: Updated API
  version: 1.0.0
servers:
  - url: https://d5***no.apigw.yandexcloud.net
paths:
  /results:
    get:
      x-yc-apigateway-integration:
        type: cloud-functions
        function_id: d4***e9
        service_account_id: aj***1r
      operationId: function-for-user-requests
  /check:
    get:
      x-yc-apigateway-integration:
        type: cloud-functions
        function_id: d4***fc
        service_account_id: aj***1r
      operationId: add-url
